# Generated by Django 2.2 on 2019-04-10 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Code')),
                ('label', models.CharField(max_length=255, verbose_name='Title')),
                ('period', models.CharField(choices=[('0', 'Do not send'), ('I', 'Send immediately'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, verbose_name='When to send the email')),
            ],
        ),
        migrations.CreateModel(
            name='UserNotificationConf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('0', 'Do not send'), ('I', 'Send immediately'), ('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1, verbose_name='When to send the email')),
                ('notification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Title')),
                ('text', models.TextField(verbose_name='Description')),
                ('receivedon', models.DateTimeField(auto_now_add=True, verbose_name='Received on')),
                ('readon', models.DateTimeField(blank=True, null=True, verbose_name='Read on')),
                ('senton', models.DateTimeField(blank=True, null=True, verbose_name='Sent on')),
                ('notification_type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notifications.NotificationType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
