# Generated by Django 2.2 on 2019-04-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
