# Generated by Django 2.2 on 2019-04-10 12:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotificationconf',
            unique_together={('user', 'notification_type')},
        ),
    ]
