# Generated by Django 2.2 on 2019-04-10 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190410_1308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='readon',
            new_name='read_on',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='senton',
            new_name='sent_on',
        ),
    ]
