# Generated by Django 2.2 on 2019-04-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190410_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtype',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Visible'),
        ),
    ]
