# Generated by Django 2.2 on 2019-04-09 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190410_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='code',
            field=models.CharField(max_length=100, unique=True, verbose_name='Code'),
        ),
    ]
