# Generated by Django 2.2 on 2019-04-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationtype_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='text_hash',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='Hash'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='once',
            field=models.BooleanField(default=False, verbose_name='Avoid multiple sends'),
        ),
    ]
